### ISSUE TITLE
Array data type added

### ISSUE THREAD

**Issue by MickeyDelp** [totalspectrum/tinyscript#10]
I have added an intrinsic integer array data type to tinyscript. The reason I did it instead of using the list type extension functions was that I wanted the data to be inside the fixed memory arena, with no malloc/free. I know the purpose of tinyscript is to be tiny, but this only added 95 lines of code.

If anyone is interested, you can get it from my fork. https://github.com/MickeyDelp/tinyscript/tree/array
There is a test script too that shows how to use arrays.

Eric, if you like it, I can do a PR.

**Comment by totalspectrum** [comment]
I think it'd be nice to have the arrays as an option under an #ifdef. I haven't had a chance to look at your fork yet but it sounds promising.

**Comment by MickeyDelp** [comment]
I can probably put the bulk of the array code behind #ifdefs. I can pull most of it into functions so there are not a million #ifdefs throughout.

By the way, the arrays are stored with the first byte being the length of the array. This method makes it easy to pass just the array pointer to C functions, and the length comes along with it.

I think I can implement strings the same way with very little additional code. I would do it the same way old VB strings were done, Where the length of the string buffer is stored just before the string data, and the pointer points to the first character of the zero terminated string.

**Comment by MickeyDelp** [comment]
Okay, completely isolated behind #ifdef ARRAY, which is defined in tinyscript.h

**Comment by totalspectrum** [comment]
I've merged the array support, with a few small changes. Thanks doing this!

**Comment by MickeyDelp** [comment]
Great! Thanks for the shoutout in the readme. 
One addition to the readme might be a mention that test\array.ts contains examples and instructions on using arrays.
