### ISSUE TITLE
ELSEIF Added

### ISSUE THREAD

**Issue by MickeyDelp** [totalspectrum/tinyscript#24]
I added elseif in this branch: https://github.com/MickeyDelp/tinyscript/tree/elseif
It is a net increase of 14 lines of code (including brackets).

The reason I did this is that elseif is much more concise syntax that will save RAM by allowing for smaller scripts. Personally, I also find it more readable.

For example, in the [test](https://github.com/MickeyDelp/tinyscript/blob/elseif/Test/elseif.ts), the elseif version is 180 bytes versus 229 bytes for the nested if/else version. And that is using tabs for indentation, not spaces.

Interested to hear feedback. Can do a PR if you like.

**Comment by totalspectrum** [comment]
That does sound like a good idea, could you send a PR for it?

Thanks!

**Comment by MickeyDelp** [comment]
PR https://github.com/totalspectrum/tinyscript/pull/26 submitted
