### ISSUE TITLE
What data types can I work with?

### ISSUE THREAD

**Issue by colesnicov** [totalspectrum/tinyscript#28]
Hello. A very interesting project, it certainly took up a lot of your time. But I want to ask: I haven't found any documentation for this, so I can't figure out how to work with strings? Thank you

**Comment by totalspectrum** [comment]
Basically the only data types are integers and arrays of integers. It is possible to treat an array as a string, in some limited cases, but it's very awkward (see Test/stdlib.ts for an example of how to put a string into the array "format" and use it in a printf call).
