### ISSUE TITLE
Return only returns from the current String, not function

### ISSUE THREAD

**Issue by daniellandau** [totalspectrum/tinyscript#5]
For example:

```
> func foo(x) { if (x > 3) { print "bar"; return 42; print "baz"; }; print "qux"; return 0 }
> print foo(1)
qux
0
> print foo(4)
bar
qux
0
```
`baz` is never printed, as it's after the `return`, but `42` is never returned, as control passes to the rest of the function, after returning from the String body of the if.

**Comment by totalspectrum** [comment]
Thanks for the bug report! I thought this would be easy to fix, but my first attempts at it failed :(. I'll try to figure something out.

**Comment by daniellandau** [comment]
I thought it would be easy too but my attempt ended up breaking function calls as parameters to function calls.

**Comment by MickeyDelp** [comment]
I don't know if this is the most efficient solution, but it works. It ignores all statements after a return until the function is done. It does not break function calls as parameters to function calls.

PR https://github.com/totalspectrum/tinyscript/pull/17

**Comment by totalspectrum** [comment]
Mickey: Thanks for your PR (and Daniel, thanks for looking at it). I haven't had a chance to look at it yet (nor at the other ones you've sent, thanks for all your work!). I hope to do so on the weekend.

**Comment by totalspectrum** [comment]
Looks like this is fixed by MickeyDelp's PR.
