### ISSUE TITLE
Carriage return should be treated as white-space

### ISSUE THREAD

**Issue by MickeyDelp** [totalspectrum/tinyscript#8]
Carriage return should be treated as white-space in order to handle Windows CRLF line endings.

static int isspace(int c)
{
    return (c == ' ') || (c == '\t') || (c == '\r');
}

**Comment by MickeyDelp** [comment]
PR https://github.com/totalspectrum/tinyscript/pull/9

**Comment by totalspectrum** [comment]
Thank you for the pull request, I've merged it.
